# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='cpv_div',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
