# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='rowid',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
