# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contract_cpv_div'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('long_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='cpv_div',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
