# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contract_rowid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuer',
            name='anb_name',
            field=models.CharField(max_length=100),
        ),
    ]
