# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171007_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Market'),
        ),
    ]
