# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171007_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_value_category',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
