# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_influence'),
    ]

    operations = [
        migrations.AddField(
            model_name='influence',
            name='market',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Market'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='influence',
            name='year',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
