# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 17:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171007_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='influence',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='winner',
            name='influence',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
