# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_levelstatecapture'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='anb_id',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuer',
            name='anb_sector',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='issuer',
            name='anb_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
