# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20171007_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='influence',
            name='infl_norm',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
