# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_influence_infl_norm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influence',
            name='bridging_capacity',
            field=models.IntegerField(null=True),
        ),
    ]
